version: '1'
services:

### MySQL Container #########################################
    mysql:
        image: mysql:5.5.54
        environment:
            - MYSQL_DATABASE=beecard
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
        container_name: mysql

### PHP-FPM Container #######################################
    phpfpm:
        image: php:7.1.5-fpm
        volumes:
            - ./www:/usr/share/nginx/html
        depends_on:
            - mysql
        links:
            - mysql
        container_name: phpfpm

### Nginx Server Container ##################################
    nginx:
        image: nginx:1.11.10
        volumes_from:
            - phpfpm
        volumes:
            - ./beecard.net:/usr/share/nginx/html
            - ./conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        links:
            - phpfpm
            - nodejs
        container_name: nginx

### Node Container ##################################
    nodejs:
        build: .
        ports:
            - "3000:3000"
        container_name: node

### phpMyAdmin Container ####################################
    myadmin:
        image: phpmyadmin/phpmyadmin:4.6.6-2
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "8080:80"
        container_name: myadmin
